declare module "carbon-components-react";
declare module "carbon-components-react/lib/components/UIShell";
declare module "@carbon/icons-react";
declare module "@carbon/icons-react/*";
declare module "@carbon/charts";
declare module "@carbon/charts-react";
declare module "emotion";
declare module "react-router-dom";
declare module "styled-components";
declare module "react-flow-renderer";
declare module "prismjs";
declare module "@carbon/pictograms-react";
declare module "@carbon/themes";
declare let module: any;
